blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/software-mansion-labs/expo-live-activity/discussions
    about: Use this section to ask questions and discuss topics that are not related to bug reports or feature requests.
    